# -*- coding: utf-8 -*-
"""Final IoT Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14EYbR7cZ_rNvHtz2QmcA1PBihiKAGM2c

# . IoT Driven - Predictive Maintenance and Performance Analytics System for Security Automation Equipment.

1. Random Forest Implementation


  Steps :-
  1. Install pip.

  2. Install If Any Dependences.

  3. Importing the Libraries.
"""

# IoT Predictive Maintenance - Random Forest Implementation

!pip install imbalanced-learn --quiet

# STEP 1: IMPORT LIBRARIES

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix, classification_report
)
from imblearn.over_sampling import SMOTE

warnings.filterwarnings("ignore")


# DEFINING RANDOM FOREST PREDICTIVE MAINTENANCE CLASS


class RandomForestPredictiveMaintenance:

    def __init__(self):
        self.model = None
        self.scaler = StandardScaler()
        self.feature_names = None
        self.results = {}


    # STEP 1: DATASET GENERATION


    def generate_synthetic_data(self, n_samples=30000):
        print("\nSTEP 1: GENERATING SYNTHETIC DATASET")

        np.random.seed(42)

        data = {
            "hour_of_day": np.random.randint(0, 24, n_samples),
            "day_of_week": np.random.randint(0, 7, n_samples),
            "month": np.random.randint(1, 13, n_samples),
            "daily_cycle_count": np.random.uniform(50, 1200, n_samples),
            "motor_temp_current": np.random.uniform(25, 85, n_samples),
            "motor_current": np.random.uniform(2, 15, n_samples),
            "vibration_peak": np.random.uniform(0, 50, n_samples),
            "days_since_preventive": np.random.uniform(0, 180, n_samples),
            "ambient_temp": np.random.uniform(10, 45, n_samples),
            "humidity": np.random.uniform(30, 95, n_samples)
        }

        risk = (
            (data["motor_temp_current"] / 100) +
            (data["motor_current"] / 20) +
            (data["vibration_peak"] / 60) +
            (data["days_since_preventive"] / 200)
        )

        failure = np.where(
            np.random.rand(n_samples) < (0.08 * risk),
            np.random.randint(1, 6, n_samples),
            0
        )

        data["failure_type"] = failure

        df = pd.DataFrame(data)

        print("Total samples:", len(df))
        print("Failure rate:", (df["failure_type"] != 0).mean() * 100, "%")

        return df


    # STEP 2: DATA PREPARATION


    def prepare_data(self, df):
        print("\nSTEP 2: DATA PREPARATION")

        X = df.drop("failure_type", axis=1)
        y = df["failure_type"]
        self.feature_names = X.columns.tolist()

        X_train, X_temp, y_train, y_temp = train_test_split(
            X, y, test_size=0.30, stratify=y, random_state=42
        )

        X_val, X_test, y_val, y_test = train_test_split(
            X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=42
        )

        print("Train:", len(X_train))
        print("Validation:", len(X_val))
        print("Test:", len(X_test))

        smote = SMOTE(random_state=42)
        X_train, y_train = smote.fit_resample(X_train, y_train)

        X_train = self.scaler.fit_transform(X_train)
        X_val = self.scaler.transform(X_val)
        X_test = self.scaler.transform(X_test)

        return X_train, X_val, X_test, y_train, y_val, y_test


    # STEP 3: MODEL TRAINING

    def train_model(self, X_train, y_train):
        print("\nSTEP 3: TRAINING RANDOM FOREST")

        param_grid = {
            "n_estimators": [100],
            "max_depth": [20, 25],
            "min_samples_split": [5],
            "max_features": ["sqrt"],
            "class_weight": ["balanced"]
        }

        rf = RandomForestClassifier(random_state=42, n_jobs=-1)

        grid = GridSearchCV(
            rf,
            param_grid,
            cv=3,
            scoring="f1_weighted",
            n_jobs=-1
        )

        grid.fit(X_train, y_train)
        self.model = grid.best_estimator_

        print("Best Parameters:", grid.best_params_)


    # STEP 4: MODEL EVALUATION


    def evaluate_model(self, X_test, y_test):
        print("\nSTEP 4: MODEL EVALUATION")

        y_pred = self.model.predict(X_test)

        self.results["accuracy"] = accuracy_score(y_test, y_pred)
        self.results["precision"] = precision_score(y_test, y_pred, average="weighted")
        self.results["recall"] = recall_score(y_test, y_pred, average="weighted")
        self.results["f1"] = f1_score(y_test, y_pred, average="weighted")
        self.results["confusion_matrix"] = confusion_matrix(y_test, y_pred)

        print("\nAccuracy:", self.results["accuracy"])
        print("Precision:", self.results["precision"])
        print("Recall:", self.results["recall"])
        print("F1 Score:", self.results["f1"])

        print("\nClassification Report:\n")
        print(classification_report(y_test, y_pred))

        return y_pred


    # STEP 5: VISUALIZATION


    def plot_results(self, y_test, y_pred):
        print("\nSTEP 5: GENERATING PLOTS")

        plt.figure(figsize=(6, 5))
        sns.heatmap(
            confusion_matrix(y_test, y_pred),
            annot=True,
            fmt="d",
            cmap="Blues"
        )
        plt.title("Confusion Matrix")
        plt.xlabel("Predicted")
        plt.ylabel("Actual")
        plt.savefig("random_forest_results.png", dpi=300)
        plt.show()

        print("Plot saved as random_forest_results.png")


# MAIN EXECUTION


def main():
    print("\nIOT PREDICTIVE MAINTENANCE - RANDOM FOREST (COLAB READY)")

    model = RandomForestPredictiveMaintenance()

    df = model.generate_synthetic_data(n_samples=30000)
    X_train, X_val, X_test, y_train, y_val, y_test = model.prepare_data(df)
    model.train_model(X_train, y_train)
    y_pred = model.evaluate_model(X_test, y_test)
    model.plot_results(y_test, y_pred)

    print("\nEXECUTION COMPLETED SUCCESSFULLY")

# Run Program
main()

"""2. DECISION TREE With ( CART )."""

# IoT PREDICTIVE MAINTENANCE – DECISION TREE (GOOGLE COLAB READY)
# Security Automation Equipment Failure Prediction


# . STEP 0: INSTALL REQUIRED LIBRARIES

!pip install -q imbalanced-learn

#  . STEP 1: IMPORT LIBRARIES

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report
from imblearn.over_sampling import SMOTE

#.STEP 2: CLASS DEFINITION

class DecisionTreePredictiveMaintenance:

    def __init__(self):
        self.model = None
        self.scaler = StandardScaler()
        self.feature_names = None
        self.results = {}

    # . STEP 3: DATASET GENERATION

    def generate_synthetic_data(self, n_samples=20000):
        print("\nSTEP 1: Generating Synthetic Dataset")

        np.random.seed(42)

        data = {
            'motor_temp_current': np.random.uniform(25, 85, n_samples),
            'motor_current': np.random.uniform(2, 15, n_samples),
            'vibration_peak': np.random.uniform(0, 50, n_samples),
            'ambient_temp': np.random.uniform(10, 45, n_samples),
            'humidity': np.random.uniform(30, 95, n_samples),
            'days_since_preventive': np.random.uniform(0, 180, n_samples),
            'load_percentage': np.random.uniform(40, 100, n_samples),
            'daily_cycle_count': np.random.uniform(50, 1200, n_samples)
        }

        risk_score = (
            (data['motor_temp_current'] / 100) +
            (data['motor_current'] / 20) +
            (data['vibration_peak'] / 60) +
            (data['days_since_preventive'] / 200)
        )

        failure_probability = 0.08
        failure = np.random.rand(n_samples) < (failure_probability * (1 + risk_score))

        failure_type = np.where(
            failure,
            np.random.choice([1, 2, 3, 4], n_samples),
            0
        )

        data['failure_type'] = failure_type

        df = pd.DataFrame(data)

        print(f"Dataset Generated: {df.shape[0]} rows, {df.shape[1]} columns")
        print(f"Failure Rate: {(df['failure_type'] != 0).mean() * 100:.2f}%")

        return df

    # . STEP 4: DATA PREPARATION
    def prepare_data(self, df):
        print("\nSTEP 2: Data Preparation")

        X = df.drop('failure_type', axis=1)
        y = df['failure_type']
        self.feature_names = X.columns.tolist()

        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42, stratify=y
        )

        smote = SMOTE(random_state=42)
        X_train, y_train = smote.fit_resample(X_train, y_train)

        X_train = self.scaler.fit_transform(X_train)
        X_test = self.scaler.transform(X_test)

        print("Data split & balanced successfully")

        return X_train, X_test, y_train, y_test

    #. STEP 5: MODEL TRAINING
    def train_model(self, X_train, y_train):
        print("\nSTEP 3: Training Decision Tree Model")

        param_grid = {
            'max_depth': [10, 20],
            'min_samples_split': [2, 10],
            'min_samples_leaf': [1, 4],
            'criterion': ['gini']
        }

        dt = DecisionTreeClassifier(class_weight='balanced', random_state=42)

        grid = GridSearchCV(
            dt,
            param_grid,
            cv=3,
            scoring='f1_weighted',
            n_jobs=-1
        )

        grid.fit(X_train, y_train)

        self.model = grid.best_estimator_

        print("Best Parameters:", grid.best_params_)

    # STEP 6: MODEL EVALUATION

    def evaluate_model(self, X_test, y_test):
        print("\nSTEP 4: Model Evaluation")

        y_pred = self.model.predict(X_test)

        self.results['accuracy'] = accuracy_score(y_test, y_pred)
        self.results['precision'] = precision_score(y_test, y_pred, average='weighted')
        self.results['recall'] = recall_score(y_test, y_pred, average='weighted')
        self.results['f1'] = f1_score(y_test, y_pred, average='weighted')

        print(f"Accuracy : {self.results['accuracy']:.4f}")
        print(f"Precision: {self.results['precision']:.4f}")
        print(f"Recall   : {self.results['recall']:.4f}")
        print(f"F1-Score : {self.results['f1']:.4f}")

        print("\nClassification Report:\n")
        print(classification_report(y_test, y_pred))

        return y_test, y_pred

    # .  STEP 7: VISUALIZATION
    def plot_results(self, y_test, y_pred):
        print("\nSTEP 5: Generating Plots")

        cm = confusion_matrix(y_test, y_pred)

        plt.figure(figsize=(6, 5))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Greens')
        plt.title("Confusion Matrix - Decision Tree")
        plt.xlabel("Predicted")
        plt.ylabel("Actual")
        plt.savefig("decision_tree_confusion_matrix.png")
        plt.show()

        importances = pd.Series(
            self.model.feature_importances_,
            index=self.feature_names
        ).sort_values(ascending=False)

        importances.plot(kind='bar', figsize=(8, 4))
        plt.title("Feature Importance")
        plt.ylabel("Importance")
        plt.savefig("decision_tree_feature_importance.png")
        plt.show()

# . STEP 8: MAIN EXECUTION

def main():
    print("\nIoT PREDICTIVE MAINTENANCE USING DECISION TREE")
    print("============================================")

    model = DecisionTreePredictiveMaintenance()

    df = model.generate_synthetic_data(n_samples=20000)
    X_train, X_test, y_train, y_test = model.prepare_data(df)
    model.train_model(X_train, y_train)
    y_test, y_pred = model.evaluate_model(X_test, y_test)
    model.plot_results(y_test, y_pred)

    print("\n EXECUTION COMPLETED SUCCESSFULLY")

if __name__ == "__main__":
    main()

"""3 . Support Vector Machine (SVM)."""

# IoT Predictive Maintenance using Support Vector Machine (SVM)

#  STEP 0: Install Required Libraries

import sys
import subprocess

def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

install("imbalanced-learn")
install("seaborn")

# . STEP 1: Import Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report
from imblearn.over_sampling import SMOTE

# . STEP 2: Define SVM Class

class SVMPredictiveMaintenance:

    def __init__(self):
        self.model = None
        self.scaler = StandardScaler()
        self.results = {}

    # . STEP 3: Generate Synthetic Dataset

    def generate_synthetic_data(self, n_samples=10000):

        np.random.seed(42)

        motor_temp = np.random.uniform(25, 85, n_samples)
        motor_current = np.random.uniform(2, 15, n_samples)
        vibration = np.random.uniform(0, 50, n_samples)
        days_since_maintenance = np.random.uniform(0, 180, n_samples)
        ambient_temp = np.random.uniform(15, 45, n_samples)
        humidity = np.random.uniform(30, 95, n_samples)

        risk_score = (
            (motor_temp - 25) / 60 +
            (motor_current - 2) / 13 +
            (vibration / 50) +
            (days_since_maintenance / 180)
        )

        failure_prob = 0.08
        failure = np.where(
            np.random.rand(n_samples) < failure_prob * (1 + risk_score),
            np.random.randint(1, 6, n_samples),
            0
        )

        df = pd.DataFrame({
            "motor_temp": motor_temp,
            "motor_current": motor_current,
            "vibration": vibration,
            "days_since_maintenance": days_since_maintenance,
            "ambient_temp": ambient_temp,
            "humidity": humidity,
            "failure_type": failure
        })

        print("✓ Synthetic dataset generated")
        print(df.head())
        return df

    # . STEP 4: Data Preparation

    def prepare_data(self, df):

        X = df.drop("failure_type", axis=1)
        y = df["failure_type"]

        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, stratify=y, random_state=42
        )

        smote = SMOTE(random_state=42)
        X_train, y_train = smote.fit_resample(X_train, y_train)

        X_train = self.scaler.fit_transform(X_train)
        X_test = self.scaler.transform(X_test)

        return X_train, X_test, y_train, y_test

    # . STEP 5: Train SVM Model

    def train_model(self, X_train, y_train):

        param_grid = {
            "C": [1],
            "kernel": ["rbf"],
            "gamma": ["scale"],
            "class_weight": ["balanced"]
        }

        svm = SVC(probability=True, random_state=42)

        grid = GridSearchCV(
            svm,
            param_grid,
            cv=3,
            scoring="f1_weighted",
            n_jobs=-1
        )

        grid.fit(X_train, y_train)
        self.model = grid.best_estimator_

        print("SVM Model Trained")
        print("Best Parameters:", grid.best_params_)

    # . STEP 6: Evaluate Model

    def evaluate_model(self, X_test, y_test):

        y_pred = self.model.predict(X_test)

        self.results["accuracy"] = accuracy_score(y_test, y_pred)
        self.results["precision"] = precision_score(y_test, y_pred, average="weighted")
        self.results["recall"] = recall_score(y_test, y_pred, average="weighted")
        self.results["f1"] = f1_score(y_test, y_pred, average="weighted")

        print("\nMODEL PERFORMANCE")
        print("Accuracy :", self.results["accuracy"])
        print("Precision:", self.results["precision"])
        print("Recall   :", self.results["recall"])
        print("F1-Score :", self.results["f1"])

        print("\nCLASSIFICATION REPORT")
        print(classification_report(y_test, y_pred))

        return y_pred

    #.STEP 7: Plot Results

    def plot_results(self, y_test, y_pred):

        cm = confusion_matrix(y_test, y_pred)

        plt.figure(figsize=(6, 5))
        sns.heatmap(cm, annot=True, fmt="d", cmap="Purples")
        plt.title("Confusion Matrix - SVM")
        plt.xlabel("Predicted")
        plt.ylabel("Actual")
        plt.savefig("svm_results.png")
        plt.show()

        print("Confusion matrix saved as svm_results.png")

# STEP 8: Main Function

def main():

    print("IoT Predictive Maintenance using SVM\n")

    svm_model = SVMPredictiveMaintenance()

    df = svm_model.generate_synthetic_data(n_samples=10000)

    X_train, X_test, y_train, y_test = svm_model.prepare_data(df)

    svm_model.train_model(X_train, y_train)

    y_pred = svm_model.evaluate_model(X_test, y_test)

    svm_model.plot_results(y_test, y_pred)

    print("\n PROGRAM EXECUTED SUCCESSFULLY")

# .STEP 9: Run Program
if __name__ == "__main__":
    main()